import { formatCurrency } from "./currency";
import type { Order, Settings } from "../types";

export interface WhatsappVariableDoc {
  token: string;
  description: string;
  example: string;
  category: "Order Info" | "Customer" | "Items & Totals" | "Payment";
}

export const WHATSAPP_VARIABLES: WhatsappVariableDoc[] = [
  {
    token: "{order_code}",
    description: "Order unique identifier code",
    example: "NK-1024",
    category: "Order Info",
  },
  {
    token: "{order_type}",
    description: "Delivery (🚚 Delivery) or Pickup (🛍️ Pickup)",
    example: "🚚 Delivery",
    category: "Order Info",
  },
  {
    token: "{eta}",
    description: "Estimated prep/delivery time",
    example: "25 mins",
    category: "Order Info",
  },
  {
    token: "{store_name}",
    description: "Store name configured in settings",
    example: "Nanami Kitchen",
    category: "Order Info",
  },
  {
    token: "{customer_name}",
    description: "Customer's full name",
    example: "Sarah Miller",
    category: "Customer",
  },
  {
    token: "{customer_phone}",
    description: "Customer's WhatsApp contact number",
    example: "0812345678",
    category: "Customer",
  },
  {
    token: "{delivery_address}",
    description: "Delivery destination street address",
    example: "12 Rosebank Rd",
    category: "Customer",
  },
  {
    token: "{delivery_note}",
    description: "Customer delivery note / landmarks",
    example: "Gate code #401",
    category: "Customer",
  },
  {
    token: "{maps_link}",
    description: "Google Maps navigation link for courier",
    example: "https://www.google.com/maps?q=-22.560900,17.065800",
    category: "Customer",
  },
  {
    token: "{items}",
    description: "List of ordered items with qty, modifiers & notes",
    example: "• 2x Bento Box (Large)...",
    category: "Items & Totals",
  },
  {
    token: "{items_count}",
    description: "Total count of individual items in cart",
    example: "3 items",
    category: "Items & Totals",
  },
  {
    token: "{subtotal}",
    description: "Items subtotal before discount/delivery",
    example: "N$ 190",
    category: "Items & Totals",
  },
  {
    token: "{vat}",
    description: "VAT tax amount (if VAT is enabled)",
    example: "N$ 28.50",
    category: "Items & Totals",
  },
  {
    token: "{discount}",
    description: "Voucher discount amount",
    example: "N$ 20",
    category: "Items & Totals",
  },
  {
    token: "{voucher_code}",
    description: "Applied voucher promo code",
    example: "NANAMI20",
    category: "Items & Totals",
  },
  {
    token: "{delivery_fee}",
    description: "Calculated delivery fee",
    example: "N$ 25",
    category: "Items & Totals",
  },
  {
    token: "{total}",
    description: "Final total payable amount",
    example: "N$ 215",
    category: "Items & Totals",
  },
  {
    token: "{payment_method}",
    description: "Selected payment option",
    example: "Bank Transfer / EFT",
    category: "Payment",
  },
];

export const WHATSAPP_PRESETS = {
  standard: {
    name: "Standard Detailed",
    description:
      "Comprehensive breakdown with emojis, customer details, item options, and payment summary.",
    header: "*NEW ORDER #{order_code}*",
    footer:
      "_Hello Admin / Owner, I have placed the order above via {store_name}. Please confirm and process my order. Thank you!_",
    template: `*NEW ORDER #{order_code}*
------------------------------------------
👤 *CUSTOMER DETAILS:*
• Name: {customer_name}
• WhatsApp No: {customer_phone}
• Order Type: {order_type}
{delivery_address_block}
{maps_link_block}
{delivery_note_block}
------------------------------------------
🍱 *ORDERED ITEMS:*
{items}
------------------------------------------
💵 *PAYMENT SUMMARY:*
• Items Subtotal: {subtotal}
{vat_block}
{discount_block}
{delivery_fee_block}
*💰 TOTAL AMOUNT: {total}*
------------------------------------------
💳 *PAYMENT METHOD (MANUAL):*
• {payment_method}

_Hello Admin / Owner, I have placed the order above via {store_name}. Please confirm and process my order. Thank you!_`,
  },
  compact: {
    name: "Compact & Fast",
    description: "Streamlined format optimized for busy kitchen staff and fast ticket review.",
    header: "🧾 *ORDER #{order_code}* — {order_type}",
    footer: "_Auto-generated by {store_name} Checkout_",
    template: `🧾 *ORDER #{order_code}* ({order_type})
Customer: *{customer_name}* ({customer_phone})
{delivery_address_block}
{maps_link_block}

🍱 *ITEMS ({items_count}):*
{items}

💰 *TOTAL: {total}* ({payment_method})
{discount_block}
_Auto-generated by {store_name} Checkout_`,
  },
  receipt: {
    name: "Receipt Ticket",
    description: "Classic clean receipt layout with dashed borders and aligned totals.",
    header:
      "==============================\n   {store_name} RECEIPT\n==============================",
    footer:
      "==============================\n Thank you for your order!\n==============================",
    template: `==============================
       {store_name}
==============================
Order Code : #{order_code}
Order Type : {order_type}
Customer   : {customer_name}
Contact    : {customer_phone}
{delivery_address_block}
{maps_link_block}
------------------------------
ITEMS:
{items}
------------------------------
Subtotal   : {subtotal}
{delivery_fee_block}
{discount_block}
TOTAL      : {total}
Payment    : {payment_method}
==============================
 Thank you for ordering!
==============================`,
  },
};

export function cleanWhatsappNumber(raw?: string) {
  if (!raw) return "27812345678";
  let cleaned = raw.replace(/\D/g, "");
  if (cleaned.startsWith("0")) {
    cleaned = "27" + cleaned.slice(1);
  }
  return cleaned || "27812345678";
}

export function formatWhatsappDisplayNumber(raw?: string): string {
  const cleaned = cleanWhatsappNumber(raw);
  if (cleaned.startsWith("27") && cleaned.length >= 11) {
    // South Africa format: +27 81 234 5678
    return `+27 ${cleaned.slice(2, 4)} ${cleaned.slice(4, 7)} ${cleaned.slice(7)}`;
  }
  if (cleaned.startsWith("62") && cleaned.length >= 10) {
    // Indonesia format: +62 812-3456-7890
    return `+62 ${cleaned.slice(2, 5)}-${cleaned.slice(5, 9)}-${cleaned.slice(9)}`;
  }
  if (cleaned.startsWith("1") && cleaned.length === 11) {
    // US / CA format: +1 (800) 555-0199
    return `+1 (${cleaned.slice(1, 4)}) ${cleaned.slice(4, 7)}-${cleaned.slice(7)}`;
  }
  return `+${cleaned}`;
}

export function buildWhatsappMessage(
  order: Order,
  currencyOrSettings: string | Partial<Settings> = "N$",
): string {
  const settings: Partial<Settings> =
    typeof currencyOrSettings === "object" && currencyOrSettings !== null
      ? currencyOrSettings
      : { currencySymbol: typeof currencyOrSettings === "string" ? currencyOrSettings : "N$" };

  const currencySymbol = settings.currencySymbol || "N$";
  const rupiah = (n: number) => formatCurrency(n, currencySymbol);

  // If a custom template is defined and not just default/empty
  const customTemplate = settings.whatsappTemplate?.trim();
  const storeName = settings.storeName || "Nanami Kitchen";

  // Formatted item lines
  const lines = order.lines
    .map(
      (l) =>
        `• *${l.qty}x ${l.name}*${l.optionLabels && l.optionLabels.length ? ` (${l.optionLabels.join(", ")})` : ""}${
          l.note ? `\n  Note: ${l.note}` : ""
        }\n  Subtotal: ${rupiah(l.unitPrice * l.qty)}`,
    )
    .join("\n\n");

  const itemsCount = order.lines.reduce((sum, l) => sum + (l.qty || 1), 0);

  const mapsLink =
    order.customer.mapsUrl ||
    (order.customer.lat !== undefined && order.customer.lng !== undefined
      ? `https://www.google.com/maps?q=${order.customer.lat.toFixed(6)},${order.customer.lng.toFixed(6)}`
      : "");
  const mapsLinkBlock = order.type === "delivery" && mapsLink ? `• Maps Location: ${mapsLink}` : "";

  if (customTemplate) {
    const deliveryAddressBlock =
      order.type === "delivery" ? `• Delivery Address: ${order.customer.address || "N/A"}` : "";
    const deliveryNoteBlock = order.customer.deliveryNote
      ? `• Location Note: ${order.customer.deliveryNote}`
      : "";
    const vatBlock =
      order.vatAmount && order.vatAmount > 0
        ? `• VAT (${order.vatPercent ?? 15}%): ${rupiah(order.vatAmount)}`
        : "";
    const discountBlock = order.discount
      ? `• Voucher Discount${order.voucherCode ? ` (${order.voucherCode})` : ""}: -${rupiah(order.discount)}`
      : "";
    const deliveryFeeBlock =
      order.type === "delivery" ? `• Delivery Fee: ${rupiah(order.deliveryFee)}` : "";

    let result = customTemplate
      .replace(/{order_code}/g, order.code)
      .replace(/{store_name}/g, storeName)
      .replace(/{customer_name}/g, order.customer.name || "Customer")
      .replace(/{customer_phone}/g, order.customer.phone || "")
      .replace(/{order_type}/g, order.type === "delivery" ? "🚚 Delivery" : "🛍️ Pickup (Takeaway)")
      .replace(/{delivery_address_block}/g, deliveryAddressBlock)
      .replace(/{delivery_address}/g, order.customer.address || "")
      .replace(/{customer_address}/g, order.customer.address || "")
      .replace(/{maps_link_block}/g, mapsLinkBlock)
      .replace(/{maps_link}/g, mapsLink)
      .replace(/{delivery_note_block}/g, deliveryNoteBlock)
      .replace(/{delivery_note}/g, order.customer.deliveryNote || "")
      .replace(/{customer_notes}/g, order.customer.deliveryNote || "")
      .replace(/{items}/g, lines)
      .replace(/{items_count}/g, `${itemsCount} item${itemsCount > 1 ? "s" : ""}`)
      .replace(/{subtotal}/g, rupiah(order.subtotal))
      .replace(/{vat_block}/g, vatBlock)
      .replace(/{vat}/g, order.vatAmount ? rupiah(order.vatAmount) : rupiah(0))
      .replace(/{discount_block}/g, discountBlock)
      .replace(/{discount}/g, order.discount ? rupiah(order.discount) : rupiah(0))
      .replace(/{voucher_code}/g, order.voucherCode || "")
      .replace(/{delivery_fee_block}/g, deliveryFeeBlock)
      .replace(/{delivery_fee}/g, rupiah(order.deliveryFee))
      .replace(/{total}/g, rupiah(order.total))
      .replace(/{payment_method}/g, order.paymentMethod || "Cash")
      .replace(/{eta}/g, order.etaMinutes ? `${order.etaMinutes} mins` : "15-30 mins");

    // Clean up any double blank lines from empty blocks
    result = result.replace(/\n{3,}/g, "\n\n").trim();
    return result;
  }

  // Default Standard WhatsApp Template (100% backward compatible with regression tests)
  const header = settings.whatsappHeader?.trim() || `*NEW ORDER #${order.code}*`;
  const footer =
    settings.whatsappFooter?.trim() ||
    `_Hello Admin / Owner, I have placed the order above via ${storeName}. Please confirm and process my order. Thank you!_`;

  return [
    header.replace(/{order_code}/g, order.code).replace(/{store_name}/g, storeName),
    `------------------------------------------`,
    `👤 *CUSTOMER DETAILS:*`,
    `• Name: ${order.customer.name}`,
    `• WhatsApp No: ${order.customer.phone}`,
    `• Order Type: ${order.type === "delivery" ? "🚚 Delivery" : "🛍️ Pickup (Takeaway)"}`,
    order.type === "delivery" ? `• Delivery Address: ${order.customer.address}` : "",
    mapsLinkBlock,
    order.customer.deliveryNote ? `• Location Note: ${order.customer.deliveryNote}` : "",
    `------------------------------------------`,
    `🍱 *ORDERED ITEMS:*`,
    lines,
    `------------------------------------------`,
    `💵 *PAYMENT SUMMARY:*`,
    `• Items Subtotal: ${rupiah(order.subtotal)}`,
    order.vatAmount && order.vatAmount > 0
      ? `• VAT (${order.vatPercent ?? 15}%): ${rupiah(order.vatAmount)}`
      : "",
    order.discount
      ? `• Voucher Discount${order.voucherCode ? ` (${order.voucherCode})` : ""}: -${rupiah(order.discount)}`
      : "",
    order.type === "delivery" ? `• Delivery Fee: ${rupiah(order.deliveryFee)}` : "",
    `*💰 TOTAL AMOUNT: ${rupiah(order.total)}*`,
    `------------------------------------------`,
    `💳 *PAYMENT METHOD (MANUAL):*`,
    `• ${order.paymentMethod}`,
    "",
    footer.replace(/{order_code}/g, order.code).replace(/{store_name}/g, storeName),
  ]
    .filter(Boolean)
    .join("\n");
}
